### ISSUE TITLE
English page shows in Chinese

### ISSUE THREAD

**Issue by richelbilderbeek** [teuder/rcpp_intro#3]
I viewed https://teuder.gitbooks.io/introduction-to-rcpp/content/en/22_R_function.html and found it is displayed in Chinese:

![2016-11-28-184754_1600x1200_scrot](https://cloud.githubusercontent.com/assets/2098230/20679455/428e5c94-b59b-11e6-8898-10c4873a6408.png)

I guess that is incorrect :-)

Good luck fixing it :-)

**Comment by teuder** [comment]
Thank you for your comment! Actually it is Japanease ;)
I placed English page in Japanese book by mistake.
