### ISSUE TITLE
C++11 initializer list example is Japanese

### ISSUE THREAD

**Issue by richelbilderbeek** [teuder/rcpp_intro#4]
At [chapter 5](https://teuder.gitbooks.io/introduction-to-rcpp/content/en/05_c++11.html), there is a Japanese comment:

![there](https://cloud.githubusercontent.com/assets/2098230/20786579/20e21a78-b7a7-11e6-8b00-2ef61613e9bc.png)

Happy to help :+1:

**Comment by teuder** [comment]
Thanks!
I fixed the comment.
