### ISSUE TITLE
Data frame chapter is Japanese

### ISSUE THREAD

**Issue by richelbilderbeek** [teuder/rcpp_intro#5]
The [data frame chapter](https://teuder.gitbooks.io/introduction-to-rcpp/content/en/13_dataframe.html) is Japanese

![issue](https://cloud.githubusercontent.com/assets/2098230/20786660/97d30e9e-b7a7-11e6-890b-2f3b98deac32.png)

Always happy to help :+1:

**Comment by richelbilderbeek** [comment]
When going to another page and back, the problem is fixed.

![issue](https://cloud.githubusercontent.com/assets/2098230/20786692/d3d69028-b7a7-11e6-9e81-11c779d1e597.png)

Thus, the problem is at the webpage :sunglasses: 

Good luck fixing!

**Comment by teuder** [comment]
You may have seen the browser's cache.
Anyway, thank you for the report !
